
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bloggingapp-deployment
  namespace: webapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bloggingapp
  template:
    metadata:
      labels:
        app: bloggingapp
    spec:
      containers:
        - name: bloggingapp
          image: shreyasriballa/bloggingapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: bloggingapp-ssvc
  namespace: webapps
spec:
  selector:
    app: bloggingapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
